#Config file for DC load 0.1 PC gui

#Author: Brandon

#Date created: 27/09/2026

[device]
baudrate = 115200
record_terminator = '\r' #comes after every frame of data
data_size = 8 #bits


[registers]
order = status, voltage, current

[register.status]
name = Status Register
decoder = status_bits
packet_with_bits = 8

[register.voltage]
name = Voltage
decoder = uint16_be
scale = 0.01
unit = V
packet_with_bits = 16

[register.current]
name = Current
decoder = uint16_be
scale = 0.001
unit = A
packet_with_bits = 16

[decoder.status_bits]
type = individual_bits
1 = mode_cc
2 = mode_cv
3 = edit_mode
4 = error
5 = placeholder
6 = placeholder
7 = placeholder
8 = placeholder
